version: "2"

services:
  backend:
    image: nbe95/keinplan-backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEINPLAN_HYPERLINK=https://your-keinplan-server.tld/
      - KAPLAN_ALLOWED_SERVERS=comma_separated_list_of_allowed_servers
      - KAPLAN_ALLOWED_WORKGROUPS=comma_separated_list_of_allowed_workgroups
