ARG PYTHON_BASE=3.14-slim

FROM python:$PYTHON_BASE

WORKDIR /app

# Install TeX Live
RUN apt-get update && apt-get install -y --no-install-recommends \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-science \
    texlive-fonts-recommended \
    lmodern \
    locales \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Setup German locale
RUN sed -i '/de_DE.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen
ENV LC_ALL=de_DE.utf8
