name: Deploy by webhook

on:
  workflow_call:
    secrets:
      webhook:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Call deployment webhook
        run: |
          curl -s -X POST "${{ secrets.webhook }}"
