name: Deploy by webhook

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      tag:
        type: string
        default: latest
    secrets: inherit

jobs:
  deploy:
    name: Deploy to ${{ inputs.target }}
    environment:
      name: ${{ inputs.target}}
      url: ${{ env.DEPLOYMENT_URL }}
    ns-on: ubuntu-latest
    steps:
      - name: Call deployment webhook
        run: |
          curl -s -X POST "${{ secrets.DEPLOYMENT_WEBHOOK }}?DEPLOY_TAG=${{ inputs.tag }}"
