name: Lint

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint-backend:
    name: Lint the backend code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pdm sync -d
      - name: Run linters
        run: |
          pdm run lint

  lint-frontend:
    name: Lint the frontend code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dev-dependencies
        run: |
          npm install --only=dev
      - name: Run linters
        run: |
          npm run lint
      - name: Perform type check
        run: |
          npx tsc

  validate-release:
    name: Validate release label and notes
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.7.0
        name: Bump and tag new version
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          noop-labels: ""
          require-release-notes: false
          base-branch: true
          with-v: false
