name: Create and publish release

on:
  push:
    branches:
      - main

env:
  BACKEND_IMAGE_NAME: nbe95/keinplan-backend
  FRONTEND_IMAGE_NAME: nbe95/keinplan-frontend

jobs:
  bump-tag-version:
    name: Bump and tag new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Bump and tag new version
        id: semver
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          noop-labels: ""
          require-release-notes: false
          base-branch: true
          with-v: false

  create-docker-images:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    needs: [bump-tag-version]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          file: ./backend/Dockerfile
          context: ./backend/
          build-args: |
            VERSION=${{ needs.bump-tag-version.outputs.version }}
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:${{ needs.bump-tag-version.outputs.version }}
            ${{ env.BACKEND_IMAGE_NAME }}:latest
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          file: ./frontend/Dockerfile
          context: ./frontend/
          build-args: |
            VERSION=${{ needs.bump-tag-version.outputs.version }}
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ needs.bump-tag-version.outputs.version }}
            ${{ env.FRONTEND_IMAGE_NAME }}:latest
